version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - .:/app

  frontend:
    image: node:18-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev --host 0.0.0.0"
